[profile.default]
src  = "src"
out  = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 20_000

remappings = [
  "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
  "@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts",
  "solmate=lib/solmate/src",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fmt] # See https://book.getfoundry.sh/reference/config/formatter
int_types             = "long"
line_length           = 120
bracket_spacing       = true
multiline_func_header = "all"
number_underscore     = "thousands"
quote_style           = "double"
sort_imports          = true
ignore                = ['./lib/**/*']
