sequenceDiagram
    title Farm Manager Claim And Stake Flow
    
    actor User
    participant FarmManager
    participant Farm
    participant RewardFarm
    participant RewardToken

    %% Claim And Stake Flow
    rect rgb(220, 220, 255)
        Note over User,RewardToken: Claim And Stake Flow
        User->>+FarmManager: claimAndStake(claimAndStakeParams)
        FarmManager->>+Farm: forceClaim(amount, owner, farmManager)
        Farm->>Farm: _beforeForceClaim()
        Farm->>Farm: _updateReward(owner)
        Farm->>Farm: _updatePendingReward()
        Farm->>FarmManager: mintRewardCallback(farmManager, amount)
        FarmManager->>RewardToken: mint(farmManager, amount)
        Farm-->>-FarmManager: emit ForceClaimed(amount, owner, farmManager)
        
        FarmManager->>RewardToken: approve(farmManager, amount)
        FarmManager->>+RewardFarm: depositERC20(amount, farmManager, receiver)
        RewardFarm->>RewardFarm: _beforeDeposit()
        RewardFarm->>RewardFarm: _updateReward(receiver)
        RewardToken->>RewardFarm: transferFrom(farmManager, rewardFarm, amount)
        RewardFarm->>RewardFarm: _updateShares()
        RewardFarm-->>-FarmManager: emit Deposit(amount, farmManager, receiver)
        
        FarmManager-->>-User: return (claimedAmount, stakedAmount)
    end 